---
title: "Data Analysis"
output: html_document
---


```{r load-packages, message=FALSE}
library(tidyverse)
library(broom)
library(readr)
library(tidymodels)
library(openintro)
#devtools::install_github("jennybc/gapminder")
library(gapminder)
```


```{r upload-data}
Summer_olympics <- read_csv("Summer-Olympic-medals-1976-to-2008.csv")
Country_codes <-read_csv("coutry-and-continent-codes.csv")
gdp_data <- read_csv("gdp_data.csv")
```
```{r homogenizing-data}
names(gapminder)[1] <- 'Country'

gapminder_summary <-gapminder %>%
   select(Country, year, pop) %>%
   filter(year == c(1992, 1997, 2002, 2007)) %>%
   select(Country, pop) %>%
   group_by(Country) %>%
   summarise(pop = mean(pop)) 
```

```{r augmenting-data}
#names(Country_codes)[names(Country_codes) == 'Three_Letter_Country_Code'] <- 'Country_code'
Olympic_final <- Summer_olympics %>%
   left_join(
      Country_codes, 
      by = c("Country_Code" = "Three_Letter_Country_Code") ) %>%
   mutate(
      Medal_value = case_when(
      Medal == "Gold" ~ 3,
      Medal == "Silver" ~ 2,
      Medal == "Bronze" ~ 1)) %>%
   filter(Year == c(1996, 2000, 2004, 2008)) %>%
   left_join(
      gapminder_summary,
      by= c("Country")
   ) %>%
   mutate(pop = case_when(
      Country_Name == "Russian Federation" ~ 144000000,
      Country_Name == "Korea, Republic of" ~ 48000000,
      Country_Name == "Ukraine" ~ 47500000,
      Country_Name == "Khazakstan, Republic of" ~ 15000000,
      TRUE ~ pop))
```


```{r summarising-medals}
#Creating Bronze, Silver, and Gold columns and removing excess
Olympic_collapse <- Olympic_final %>%
  group_by(Country) %>%
  mutate(
  Bronze = sum(str_count(Medal, "Bronze")),
  Silver = sum(str_count(Medal, "Silver")),
  Gold = sum(str_count(Medal, "Gold"))) %>%
  select(Country, Medal, Continent_Name) %>%
  group_by(Country, Medal) %>%
  mutate(Continent_Name = case_when(
      Country %in% c("Germany", "Netherlands", "Yugoslavia", "Bulgaria",
                     "Switzerland", "Slovenia", "Denmark", "Croatia", "Greece",
                     "Portugal", "Serbia", "Latvia") ~ "Europe",
      Country %in% c("Bahamas", "Costa Rica") ~ "North America",
      Country %in% c("Trinidad and Tobago", "Chile", "Paraguay") ~ "South America",
      Country %in% c("Indonesia", "Taiwan", "Vietnam", "Iran",  "Malaysia",
                     "Mongolia") ~ "Asia",
      Country %in% c("Zimbabwe", "Nigeria", "South Africa", "Algeria") ~ "Africa",  
       TRUE    ~ Continent_Name)) %>%
  relocate(Continent_Name, .after = Country) %>%
   count(Continent_Name = Continent_Name)%>%
  pivot_wider(names_from = Medal, values_from = n) %>%
  mutate_all(~replace(., is.na(.), 0)) %>%
  relocate(Gold, .after = Silver)
```

```{r Overall-graph}
Olympic_overall <- Olympic_collapse %>% 
   group_by(Country) %>%
   mutate(Medal_sum = Bronze + Silver + Gold ) %>%
   arrange(desc(Medal_sum))

Olympic_overall_tograph <- pivot_longer(Olympic_overall, cols= c("Bronze", "Silver", "Gold"), names_to="variable", values_to="value") %>%
  group_by(Country) %>%
  mutate(proportion=value/Medal_sum)

Olympic_overall_tograph %>%
  filter(Medal_sum>60) %>%
  mutate(Country_name = factor(Country, levels=c("Russia", "United States", "Australia", "Germany", "China", "Netherlands", "Cuba", "Brazil"))) %>%
  ggplot(aes(x=Country_name, y=value, fill = variable)) +
  labs(title = "Winningest Countries in the World", x = "Country", y = "Total Medal Count", fill = "Medal Type") +
  geom_col() +
  theme(axis.text.x = element_text(angle = 45))
```


```{r NA_graph}
Olympic_final %>%
   filter(Continent_Name == "North America") %>%
  ggplot(aes(x = Country, y = Medal_value, fill = Medal)) +
  geom_col()  +
  facet_wrap(~ "Continent_Name")
```

```{r Cuba_US_graph_Total_Medals}
Olympic_final %>%
   filter(Country == c("United States", "Cuba")) %>%
   ggplot(aes(x = Year, y = Medal_value, fill = Medal)) + 
   labs(x = "Year", y = "Total Medal Values", 
   title = "Total Medal Value for USA and Cuba") +
   geom_col() +
   facet_wrap(~ Country) +
   scale_x_continuous(breaks = seq(1996,2008, by = 4), labels = c("1996", "2000", "2004", "2008"))
```


```{r merging_gdp_with_olympic}
   Olympic_final_new <- merge(Olympic_final, gdp_data,
   by=c("Year","Country_Code"))
```

```{r summarise-medals-with-gdp}
Olympic_gdp<-Olympic_final_new %>%
   select(Country, Year, gdp, Medal_value, pop) %>%
   group_by(Country, Year, gdp, pop) %>%
   summarise(Medal_value=n())
```

```{r gdp-regression}
Olympic_gdp_regression <- linear_reg() %>%
   set_engine("lm") %>%
   fit(Medal_value~gdp, data = Olympic_gdp)

Olympic_gdp_regression

glance(Olympic_gdp_regression)$r.squared
 
Olympic_gdp %>%
   ungroup() %>%
   summarise(
      Average_gdp = mean(gdp),
      Median_gdp = median(gdp),
      Lowest_gdp = min(gdp),
      Highest_gdp = max(gdp)
   )
```

```{r regression-gdp}
Olympic_gdp %>%
ggplot(mapping = aes(x = gdp, y = Medal_value)) +
  geom_point(alpha = 0.5)+
  geom_jitter() +
   geom_smooth(method = "lm", se = FALSE, size = 1)
```

```{r pop-regression}
Olympic_pop_regression <- linear_reg() %>%
   set_engine("lm") %>%
   fit(Medal_value~pop, data = Olympic_gdp)

Olympic_pop_regression

glance(Olympic_pop_regression)$r.squared
 
Olympic_gdp %>%
   group_by(Country) %>%
   mutate(
      pop = mean(pop)
   ) %>%
   ungroup() %>%
   summarise(
      Average_pop = mean(pop, na.rm=TRUE),
      Median_pop = median(pop, na.rm=TRUE),
      Lowest_pop = min(pop, na.rm=TRUE),
      Highest_pop = max(pop, na.rm=TRUE)
   )
```
```{r regression-pop}
Olympic_gdp %>%
   filter(pop <= 80000000) %>%
ggplot(mapping = aes(x = pop, y = Medal_value)) +
  geom_point(alpha = 0.5)+
  geom_jitter(width = 1000000) +
   geom_smooth(method = "lm", se = FALSE, size = 1) +
  labs(title = "Regressing Population on Medal Value", y = "Total Medal Value", x = "Population")
```

```{r regression-both}
Regression_both <- linear_reg() %>%
   set_engine("lm") %>%
   fit(Medal_value~pop+gdp, data = Olympic_gdp)

glance(Regression_both)$r.squared
```


Graphs that we made but did not use in the presentation. 

```{r US_aquatics}
Olympic_final %>%
   filter(Sport == "Aquatics") %>%
   filter(Country == "United States") %>%
   ggplot(aes(x = Year, y = Medal_value, fill = Medal)) + 
   labs(x = "Year", y = "Total Medal Values", 
   title = "Total Medal Count for Aquatics for the United States") +
   geom_col() +
    scale_x_continuous(breaks = seq(1996,2008, by = 4), labels = c("1996", "2000", "2004", "2008"))
   
```

```{r China_Aquatics}
Olympic_final %>%
   filter(Sport == "Aquatics") %>%
   filter(Country == "Russia") %>%
   ggplot(aes(x = Year, y = Medal_value, fill = Medal)) + 
   labs(x = "Year", y = "Total Medal Values", 
   title = "Total Medal Count for Aquatics for Russia") +
   geom_col() +
   scale_x_continuous(breaks = seq(1996,2008, by = 4), labels = c("1996", "2000", "2004", "2008"))
  
```

```{r US_athletics}
Olympic_final %>%
   filter(Sport == "Athletics") %>%
   filter(Country == "United States") %>%
   ggplot(aes(x = Year, y = Medal_value, fill = Medal)) + 
   labs(x = "Year", y = "Total Medal Values", 
   title = "Total Medal Count for Athletics for the United States") +
   geom_col() +
   scale_x_continuous(breaks = seq(1996,2008, by = 4), labels = c("1996", "2000", "2004", "2008"))

```

```{r Jamaica_athletics}
Olympic_final %>%
   filter(Sport == "Athletics") %>%
   filter(Country == "Jamaica") %>%
   ggplot(aes(x = Year, y = Medal_value, fill = Medal)) + 
   labs(x = "Year", y = "Total Medal Values", 
   title = "Total Medal Count for Athletics for Jamaica") +
   geom_col() +
   scale_x_continuous(breaks = seq(1996,2008, by = 4), labels = c("1996", "2000", "2004", "2008"))
```

```{r US_Rowing}
Olympic_final %>%
   filter(Sport == "Rowing") %>%
   filter(Country == "United States") %>%
   ggplot(aes(x = Year, y = Medal_value, fill = Medal)) + 
   labs(x = "Year", y = "Total Medal Values", 
   title = "Total Medal Count for Rowing for the United States") +
   geom_col() +
   scale_x_continuous(breaks = seq(1996,2008, by = 4), labels = c("1996", "2000", "2004", "2008"))

```


```{r UK_Rowing}
Olympic_final %>%
   filter(Sport == "Rowing") %>%
   filter(Country == "United Kingdom") %>%
   ggplot(aes(x = Year, y = Medal_value, fill = Medal)) + 
   labs(x = "Year", y = "Total Medal Values", 
   title = "Total Medal Count for Rowing for the United Kingdom") +
   geom_col() +
   scale_x_continuous(breaks = seq(1996,2008, by = 4), labels = c("1996", "2000", "2004", "2008"))
```

